const wrssEmails = [
    "ewa.czarnecka@samorzad.agh.edu.pl",
    "jan.kwapien@samorzad.agh.edu.pl",
    "julia.calus@samorzad.agh.edu.pl",
    "maria.nowak@samorzad.agh.edu.pl",
    "oliwia.maczka@samorzad.agh.edu.pl",
    "piotr.pietranis@samorzad.agh.edu.pl",
    "przemyslaw.szewczak@samorzad.agh.edu.pl",
    "dominik.bober@samorzad.agh.edu.pl",
    "natalia.ozarek@samorzad.agh.edu.pl",
    "remigiusz.mietla@samorzad.agh.edu.pl",
    "jakub.truszkowski@samorzad.agh.edu.pl",
    "anna.smolik@samorzad.agh.edu.pl",
    "wiktoria.sarzynska@samorzad.agh.edu.pl",
    "gabriela.rok@samorzad.agh.edu.pl",
    "hanna.grechuta@samorzad.agh.edu.pl",
    "pawel.mozgowiec@samorzad.agh.edu.pl",
    "martyna.szwaja@samorzad.agh.edu.pl",
    "marek.mrowka@samorzad.agh.edu.pl",
    "patrycja.lewicka@samorzad.agh.edu.pl",
    "milena.smolka@samorzad.agh.edu.pl",
    "kacper.iwicki@samorzad.agh.edu.pl",
    "julia.sztangreciak@samorzad.agh.edu.pl",
    "hubert.nowak@samorzad.agh.edu.pl",
    "magdalena.sroka@samorzad.agh.edu.pl",
    "httpiotrowska@gmail.com",
    "maciej.michalek@samorzad.agh.edu.pl",
    "areksw8@gmail.com",
    "oszoldra@gmail.com",
    "wera.s665@gmail.com",
    "piotr.kwapien65@gmail.com",
    "gabisz3004@gmail.com",
];

export default wrssEmails;
